package be.lacerta.cq2.sim.hbn;

// Generated 1-jun-2009 23:51:42 by Hibernate Tools 3.2.4.GA

/**
 * CreatureCurse generated by hbm2java
 */
public class CreatureCurse extends HbnObject implements java.io.Serializable {

	private String mage;
	private Skill skill;
	private Creature creature;

	public CreatureCurse() {
	}

	public CreatureCurse(String mage, Skill skill, Creature creature) {
		this.mage = mage;
		this.skill = skill;
		this.creature = creature;
	}

	public String getMage() {
		return this.mage;
	}

	public void setMage(String mage) {
		this.mage = mage;
	}

	public Skill getSkill() {
		return this.skill;
	}

	public void setSkill(Skill skill) {
		this.skill = skill;
	}

	public Creature getCreature() {
		return this.creature;
	}

	public void setCreature(Creature creature) {
		this.creature = creature;
	}

}
