package be.lacerta.cq2.sim.hbn;

// Generated 11-jun-2009 13:15:45 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Note generated by hbm2java
 */
public class Note extends HbnObject implements java.io.Serializable {

	private Integer id;
	private User user;
	private Date date;
	private String note;

	public Note() {
	}

	public Note(User user, Date date, String note) {
		this.user = user;
		this.date = date;
		this.note = note;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
