package be.lacerta.cq2.orbparser;

import java.security.InvalidParameterException;
import java.util.*;

import be.lacerta.cq2.objects.Gem;
import be.lacerta.cq2.objects.Orb;

public class OrbParser {
	List<Orb> orbs = new ArrayList<Orb>();
	HashMap<String,List<Gem>> gems = new HashMap<String,List<Gem>>();
	public List<Orb> getOrbs() {
		return orbs;
	}
	public void setOrbs(List<Orb> orbs) {
		this.orbs = orbs;
	}
	public HashMap<String, List<Gem>> getGems() {
		return gems;
	}
	public void setGems(HashMap<String, List<Gem>> gems) {
		this.gems = gems;
	}
	public void addGem(Gem gem) {
		List<Gem> l;
		if (gems.get(gem.getName()) == null) {
			l = new ArrayList<Gem>();
		} else {
			l = gems.get(gem.getName());
		}
		l.add(gem);
		Collections.sort(l);
		gems.put(gem.getName(), l);
	}
	
	public boolean addGem(String s) {
		try {
			addGem(new Gem(s));
		} catch (InvalidParameterException ipe) {
			return false;
		}
		return true;
	}
	
	public void addOrb(Orb orb) {
		for (int i=0; i<orb.getUses();i++) {
			orbs.add(orb);
		}
		//System.out.println("number of orbs: "+orbs.size());
	}
	
	public void go2() {
		List<Orb> orbs = new ArrayList<Orb>();
		for (int i=0; i<100; i++) {
			Orb o = new Orb();
			orbs.add(o);
			System.out.println(o);
		}
		for (int i=0; i<100; i++) {
			Gem g = Gem.getRandomGem();
			addGem(g);
			//System.out.println(g.toCompactString());
		}
		
    	for (Iterator<Orb> i = orbs.iterator(); i.hasNext();) {
    		Orb o = i.next();
    		boolean add=true;
    		for (Iterator<String> ii = o.getGemsigns().iterator(); ii.hasNext();) {
    			if (gems.get(ii.next()) == null) {
    				add=false;
    				break;
    			}
    		}
    		if (add) addOrb(o);
    	}
	}
	
	public void go() {
		List<Orb> orbs = new ArrayList<Orb>();

		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Aru, Efu, Jih, Len, Ner, Sah, Var, Yar. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Aru, Dun, Eno, Fau, Fih, Inu, Jih, Kih, Nis, Var. Nether spell. Itherian spell."));
		orbs.add(new Orb("Orange Orb with 3 uses remaining. Gem signs: Eda, Eno, Inu, Len, Nuy, Ruh. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 3 uses remaining. Gem signs: Aru, Dun, Efu, Eno, Jih, Var. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Fih, Inu, Kih, Mul, Uka, Yun. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Jih, Nis, Ruh, Vae, Var, Zar. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Efu, Tur, Vae, Var, Zey. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Eno, Fau, Ruh, Uza, Yun. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Fih, Ime, Inu, Vae, Yun. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Kih, Qah, Qer, Vae, Yun. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Ime, Inu, Mul, Ruh, Xil. Nether spell. Itherian spell."));
		orbs.add(new Orb("Grey Orb with 2 uses remaining. Gem signs: Chi, Fau, Fen, Fih, Ner, Xil. Nether spell. Itherian spell."));

		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Aru, Jih, Lua, Nis, Qer, Uax, Var. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Fen, Jih, Mul, Var, Xio, Yar. Nether spell. Itherian spell."));
		orbs.add(new Orb("White Orb with 2 uses remaining. Gem signs: Chi, Ime, Kih, Xis. Nether spell. Itherian spell."));
		orbs.add(new Orb("Grey Orb with 1 use remaining. Gem signs: Chi, Inu, Kih, Uax. Nether spell. Itherian spell."));
		orbs.add(new Orb("Cyan Orb with 5 uses remaining. Gem signs: Chi, Eda, Uxi, Vae. Nether spell. Itherian spell."));

		orbs.add(new Orb("Black Orb with 3 uses remaining. Gem signs: Fih, Inu, Len, Nax, Nuy, Yar. Nether spell. Itherian spell."));


		orbs.add(new Orb("Orange Orb with 3 uses remaining. Gem signs: Aner, Fih, Uka, Uza. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Aru, Efis, Eno, Fau, Fen, Mae, Tur, Zey. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Asih, Dun, Eno, Fau, Tur, Vae, Var. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Aru, Dun, Efis, Efu, Kih, Var. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 3 uses remaining. Gem signs: Aner, Dun, Efu, Jih, Tur, Var. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Asih, Efu, Eno, Kih, Ner, Tur. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Aner, Chi, Eda, Lua, Ner, Tur, Zey. Nether spell. Itherian spell."));

		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Eda, Efu, Fen, Fih, Inu, Nax, Ner, Qulah, Ruh, Uka. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 3 uses remaining. Gem signs: Efu, Eno, Fen, Nis, Ruh, Tur, Uka, Var, Yun, Zaneh. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Eda, Efis, Fen, Jih, Len, Mul, Ner, Nuy, Var, Zey. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Efu, Fen, Kih, Nis, Tur, Yar, Zaneh, Zar, Zey. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Chi, Dun, Fen, Mae, Nis, Nuy, Uka, Yun, Zaneh. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Aru, Asih, Efu, Mae, Mul, Nis, Xis, Zar, Zey. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Aner, Aru, Fau, Len, Qer, Ruh, Uka, Vae, Yun. Nether spell. Itherian spell."));
		orbs.add(new Orb("Red Orb with 2 uses remaining. Gem signs: Inu, Mul, Ner, Qah, Sah, Uza, Xis, Zaneh. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 3 uses remaining. Gem signs: Chi, Eno, Nefar, Ner, Nuy, Qah, Qer, Var. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Aru, Chi, Muena, Nis, Ruh, Tur, Yun, Zar. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Aru, Chi, Eno, Ner, Qulah, Ruh, Yun, Zar. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 3 uses remaining. Gem signs: Efis, Efu, Ime, Ruh, Xio, Zar, Zey. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 3 uses remaining. Gem signs: Dun, Eda, Eno, Inu, Nis, Xis, Zaneh. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 3 uses remaining. Gem signs: Asih, Chi, Ime, Len, Tur, Uza, Var. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Dun, Ner, Qulah, Ruh, Sah, Yar. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Chi, Efis, Efu, Nis, Nuy, Ruh. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Aner, Eda, Tur, Uka, Vae, Yar. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Efis, Fen, Tur, Uza, Zar. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Asih, Chi, Eno, Sah, Zey. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Aru, Nefar, Nis, Sah, Uka. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Efu, Fen, Inu, Nefar, Var. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Eda, Mae, Qulah, Uza, Zey. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Dun, Eno, Ime, Nefar, Zey. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Aner, Efu, Eno, Sah, Xio. Nether spell. Itherian spell."));

		orbs.add(new Orb("Black Orb with 3 uses remaining. Gem signs: Chi, Eno, Faerh, Tur, Uka, Vae. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Chi, Efu, Muena, Nis, Ruh, Xio. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Aru, Faerh, Ner, Ruh, Uka, Uyi. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Eno, Mae, Muena, Xil, Zar. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Chi, Eda, Inu, Muena, Mul, Uka, Var. Nether spell. Itherian spell."));

		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Aru, Efis, Eno, Fih, Len, Lua, Mul, Qaera, Uka, Yun. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Aner, Aru, Chi, Faerh, Fen, Jih, Kih, Uka, Uxi, Uza. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Chi, Fau, Fih, Inu, Kih, Len, Muena, Qulah, Var, Yun. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Asih, Efu, Eno, Fen, Nefar, Nis, Qah, Uax, Yar, Zey. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Aru, Efis, Jih, Kih, Lua, Nis, Qah, Uax, Uyi, Zaneh. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Aner, Aru, Eno, Faerh, Fau, Mul, Nis, Sah, Var, Yun. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Efis, Eno, Fau, Mae, Muena, Ner, Nis, Uka, Xil. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Aner, Aru, Eno, Inu, Nefar, Sah, Tur, Uza, Var. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 3 uses remaining. Gem signs: Aner, Efis, Fih, Len, Qah, Tur, Uxi, Xil. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Aner, Efis, Eno, Inu, Nis, Sah, Uxi, Var. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Efis, Fau, Fih, Lua, Mul, Nefar, Uza, Vae. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Asih, Efis, Fau, Fen, Mul, Ner, Xil, Zey. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Asih, Chi, Efis, Efu, Mul, Qah, Tur, Zar. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Aru, Asih, Chi, Eno, Nefar, Nuy, Ruh, Xil. Nether spell. Itherian spell."));
		orbs.add(new Orb("Grey Orb with 2 uses remaining. Gem signs: Aner, Eda, Fih, Qaera, Qah, Ruh, Uza. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 3 uses remaining. Gem signs: Chi, Efu, Faerh, Kih, Len, Mae, Qaera. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Dun, Eda, Efis, Qer, Ruh, Uza, Zaneh. Nether spell. Itherian spell."));
		orbs.add(new Orb("White Orb with 2 uses remaining. Gem signs: Dun, Efis, Efu, Qaera, Vae, Yun. Nether spell. Itherian spell."));
		orbs.add(new Orb("Orange Orb with 3 uses remaining. Gem signs: Aner, Dun, Efis, Len, Mul, Sah. Nether spell. Itherian spell."));
		orbs.add(new Orb("Grey Orb with 1 use remaining. Gem signs: Faerh, Mae, Muena, Xil, Yar, Yun. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 3 uses remaining. Gem signs: Aner, Aru, Efu, Faerh, Xio, Yar. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Efu, Jih, Nefar, Tur, Var, Zaneh. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Efu, Fih, Inu, Nefar, Qulah, Xis. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Efis, Eno, Mul, Nefar, Ner, Zey. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Asih, Fen, Nax, Nefar, Nis, Qer. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Asih, Fau, Qulah, Sah, Uxi, Vae. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Aner, Eno, Qulah, Uax, Vae, Zey. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 3 uses remaining. Gem signs: Efis, Lua, Nefar, Ner, Qer. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 3 uses remaining. Gem signs: Asih, Efis, Eno, Kih, Xio. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 3 uses remaining. Gem signs: Aner, Asih, Efu, Fau, Var. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Dun, Efis, Efu, Qulah, Sah. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Aner, Jih, Qulah, Uax, Uka. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Aner, Eno, Nefar, Tur, Zar. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Faerh, Fih, Muena, Xil, Xis. Nether spell. Itherian spell."));
		orbs.add(new Orb("White Orb with 1 use remaining. Gem signs: Efis, Faerh, Ruh, Tur. Nether spell. Itherian spell."));
		orbs.add(new Orb("Grey Orb with 1 use remaining. Gem signs: Aner, Qulah, Sah, Tur. Nether spell. Itherian spell."));
		orbs.add(new Orb("Blue Orb with 1 use remaining. Gem signs: Dun, Efis, Qulah. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Aner, Inu, Mae, Nefar, Qer, Qulah, Tur, Uka, Uyi, Uza. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Efis, Efu, Fau, Fih, Len, Ruh, Uax, Urtae, Zaneh, Zey. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Aner, Efu, Faerh, Jih, Nuy, Qulah, Ruh, Sah, Uka, Zey. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Aner, Efis, Efu, Inu, Mul, Qer, Qulah, Uxi, Xio, Zar. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Asih, Efis, Inu, Lua, Nuy, Qulah, Ruh, Sah, Tur. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Aru, Asih, Dun, Eda, Efis, Faerh, Fih, Lua, Mul. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Asih, Eda, Fih, Len, Nefar, Nis, Qah, Qulah, Uax. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Aner, Aru, Efis, Mae, Muena, Nis, Sah, Uza, Yar. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 3 uses remaining. Gem signs: Asih, Faerh, Fih, Inu, Nefar, Ner, Uxi, Zey. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Asih, Efis, Efu, Jih, Nis, Qer, Qulah, Uka. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Aner, Asih, Dun, Faerh, Ner, Ruh, Sah, Var. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Aner, Asih, Eda, Fen, Sah, Uka, Vae, Zaneh. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Aner, Chi, Dun, Efis, Qulah, Var, Yar. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Aru, Efis, Efu, Nefar, Uka, Var, Zaneh. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 1 use remaining. Gem signs: Aner, Asih, Efis, Efu, Sah, Tur, Uka. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Chi, Efis, Faerh, Fau, Qulah, Tur. Nether spell. Itherian spell."));
		orbs.add(new Orb("Black Orb with 2 uses remaining. Gem signs: Asih, Chi, Efis, Tur, Uka, Zaneh. Nether spell. Itherian spell."));
		orbs.add(new Orb("White Orb with 2 uses remaining. Gem signs: Faerh, Qaera, Qulah, Sah, Uka. Nether spell. Itherian spell."));
		orbs.add(new Orb("Myrtle Orb with 1 use remaining. Gem signs: Aner, Asih, Eda, Eno, Inu, Mul, Nuy, Qulah, Ruh, Uza, Zaneh. Nether spell. Itherian spell."));

		addGem("Ugly level 13 Aner Gem (insert in bag, destroy)");
		addGem("Ugly level 13 Aner Gem (insert in bag, destroy)");
		addGem("Exquisite level 13 Aner Gem (insert in bag, destroy)");
		addGem("Beautiful level 17 Aner Gem (insert in bag, destroy)");
		addGem("Ugly level 18 Aner Gem (insert in bag, destroy)");
		addGem("Exquisite level 25 Aner Gem (insert in bag, destroy)");
		addGem("Beautiful level 33 Aner Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Aner Gem (insert in bag, destroy)");
		addGem("Beautiful level 34 Aner Gem (insert in bag, destroy)");
		addGem("Beautiful level 34 Aner Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Aner Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Aner Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Aner Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Aner Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Aner Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Aner Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Aner Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Aner Gem (insert in bag, destroy)");
		addGem("Beautiful level 35 Aner Gem (insert in bag, destroy)");
		addGem("Beautiful level 35 Aner Gem (insert in bag, destroy)");
		addGem("Beautiful level 35 Aner Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Aner Gem (insert in bag, destroy)");
		addGem("Exquisite level 36 Aner Gem (insert in bag, destroy)");
		addGem("Exquisite level 36 Aner Gem (insert in bag, destroy)");
		addGem("Ugly level 37 Aner Gem (insert in bag, destroy)");
		addGem("Ugly level 37 Aner Gem (insert in bag, destroy)");
		addGem("Magnificent level 37 Aner Gem (insert in bag, destroy)");
		addGem("Magnificent level 38 Aner Gem (insert in bag, destroy)");
		addGem("Exquisite level 38 Aner Gem (insert in bag, destroy)");
		addGem("Ugly level 51 Aner Gem (insert in bag, destroy)");
		addGem("Exquisite level 53 Aner Gem (insert in bag, destroy)");
		addGem("Exquisite level 54 Aner Gem (insert in bag, destroy)");
		addGem("Exquisite level 54 Aner Gem (insert in bag, destroy)");
		addGem("Exquisite level 54 Aner Gem (insert in bag, destroy)");
		addGem("Exquisite level 54 Aner Gem (insert in bag, destroy)");
		addGem("Exquisite level 55 Aner Gem (insert in bag, destroy)");
		addGem("Exquisite level 55 Aner Gem (insert in bag, destroy)");
		addGem("Exquisite level 55 Aner Gem (insert in bag, destroy)");
		addGem("Magnificent level 56 Aner Gem (insert in bag, destroy)");
		addGem("Magnificent level 57 Aner Gem (insert in bag, destroy)");
		addGem("Magnificent level 57 Aner Gem (insert in bag, destroy)");
		addGem("Magnificent level 57 Aner Gem (insert in bag, destroy)");
		addGem("Magnificent level 57 Aner Gem (insert in bag, destroy)");
		addGem("Exquisite level 57 Aner Gem (insert in bag, destroy)");
		addGem("Exquisite level 58 Aner Gem (insert in bag, destroy)");
		addGem("Exquisite level 60 Aner Gem (insert in bag, destroy)");
		addGem("Magnificent level 62 Aner Gem (insert in bag, destroy)");
		addGem("Magnificent level 62 Aner Gem (insert in bag, destroy)");
		addGem("Magnificent level 62 Aner Gem (insert in bag, destroy)");
		addGem("Magnificent level 62 Aner Gem (insert in bag, destroy)");
		addGem("Magnificent level 62 Aner Gem (insert in bag, destroy)");
		addGem("Magnificent level 62 Aner Gem (insert in bag, destroy)");
		addGem("Magnificent level 62 Aner Gem (insert in bag, destroy)");
		addGem("Magnificent level 62 Aner Gem (insert in bag, destroy)");
		addGem("Magnificent level 69 Aner Gem (insert in bag, destroy)");
		addGem("Ugly level 1 Aru Gem (insert in bag, destroy)");
		addGem("Beautiful level 2 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 5 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 22 Aru Gem (insert in bag, destroy)");
		addGem("Beautiful level 30 Aru Gem (insert in bag, destroy)");
		addGem("Magnificent level 30 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 37 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 40 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 42 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 61 Aru Gem (insert in bag, destroy)");
		addGem("Ugly level 61 Aru Gem (insert in bag, destroy)");
		addGem("Magnificent level 14 Asih Gem (insert in bag, destroy)");
		addGem("Ugly level 18 Asih Gem (insert in bag, destroy)");
		addGem("Ugly level 19 Asih Gem (insert in bag, destroy)");
		addGem("Ugly level 21 Asih Gem (insert in bag, destroy)");
		addGem("Ugly level 21 Asih Ruby (insert in bag, destroy)");
		addGem("Exquisite level 22 Asih Gem (insert in bag, destroy)");
		addGem("Exquisite level 22 Asih Gem (insert in bag, destroy)");
		addGem("Beautiful level 25 Asih Gem (insert in bag, destroy)");
		addGem("Magnificent level 25 Asih Gem (insert in bag, destroy)");
		addGem("Magnificent level 25 Asih Gem (insert in bag, destroy)");
		addGem("Ugly level 26 Asih Gem (insert in bag, destroy)");
		addGem("Magnificent level 26 Asih Gem (insert in bag, destroy)");
		addGem("Beautiful level 28 Asih Gem (insert in bag, destroy)");
		addGem("Beautiful level 29 Asih Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Asih Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Asih Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Asih Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Asih Gem (insert in bag, destroy)");
		addGem("Magnificent level 30 Asih Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Asih Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Asih Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Asih Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Asih Gem (insert in bag, destroy)");
		addGem("Beautiful level 33 Asih Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Asih Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Asih Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Asih Gem (insert in bag, destroy)");
		addGem("Beautiful level 34 Asih Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Asih Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Asih Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Asih Gem (insert in bag, destroy)");
		addGem("Beautiful level 35 Asih Gem (insert in bag, destroy)");
		addGem("Magnificent level 35 Asih Gem (insert in bag, destroy)");
		addGem("Ugly level 37 Asih Gem (insert in bag, destroy)");
		addGem("Ugly level 37 Asih Gem (insert in bag, destroy)");
		addGem("Ugly level 37 Asih Gem (insert in bag, destroy)");
		addGem("Magnificent level 49 Asih Gem (insert in bag, destroy)");
		addGem("Exquisite level 49 Asih Gem (insert in bag, destroy)");
		addGem("Magnificent level 50 Asih Gem (insert in bag, destroy)");
		addGem("Exquisite level 52 Asih Gem (insert in bag, destroy)");
		addGem("Exquisite level 53 Asih Gem (insert in bag, destroy)");
		addGem("Exquisite level 53 Asih Gem (insert in bag, destroy)");
		addGem("Exquisite level 54 Asih Gem (insert in bag, destroy)");
		addGem("Exquisite level 54 Asih Gem (insert in bag, destroy)");
		addGem("Magnificent level 55 Asih Gem (insert in bag, destroy)");
		addGem("Magnificent level 55 Asih Gem (insert in bag, destroy)");
		addGem("Magnificent level 56 Asih Gem (insert in bag, destroy)");
		addGem("Magnificent level 56 Asih Gem (insert in bag, destroy)");
		addGem("Magnificent level 56 Asih Gem (insert in bag, destroy)");
		addGem("Magnificent level 56 Asih Gem (insert in bag, destroy)");
		addGem("Magnificent level 57 Asih Gem (insert in bag, destroy)");
		addGem("Magnificent level 57 Asih Gem (insert in bag, destroy)");
		addGem("Magnificent level 57 Asih Gem (insert in bag, destroy)");
		addGem("Exquisite level 58 Asih Gem (insert in bag, destroy)");
		addGem("Magnificent level 60 Asih Gem (insert in bag, destroy)");
		addGem("Magnificent level 61 Asih Gem (insert in bag, destroy)");
		addGem("Magnificent level 61 Asih Gem (insert in bag, destroy)");
		addGem("Ugly level 2 Chi Gem (insert in bag, destroy)");
		addGem("Ugly level 2 Chi Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Chi Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Chi Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Chi Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Chi Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Chi Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Chi Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Chi Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Chi Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Chi Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Chi Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Chi Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Chi Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Chi Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Chi Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Chi Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Chi Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Chi Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Chi Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Chi Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Chi Gem (insert in bag, destroy)");
		addGem("Ugly level 37 Chi Gem (insert in bag, destroy)");
		addGem("Ugly level 37 Chi Gem (insert in bag, destroy)");
		addGem("Ugly level 38 Chi Gem (insert in bag, destroy)");
		addGem("Ugly level 45 Chi Gem (insert in bag, destroy)");
		addGem("Beautiful level 6 Dun Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Dun Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Dun Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Dun Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Dun Gem (insert in bag, destroy)");
		addGem("Magnificent level 33 Dun Emerald (insert in bag, destroy)");
		addGem("Ugly level 34 Dun Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Dun Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Dun Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Dun Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Dun Gem (insert in bag, destroy)");
		addGem("Ugly level 37 Dun Gem (insert in bag, destroy)");
		addGem("Ugly level 5 Eda Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Eda Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Eda Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Eda Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Eda Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Eda Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Eda Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Eda Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Eda Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Eda Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Eda Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Eda Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Eda Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Eda Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Eda Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Eda Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Eda Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Eda Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Eda Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Eda Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Eda Gem (insert in bag, destroy)");
		addGem("Ugly level 37 Eda Gem (insert in bag, destroy)");
		addGem("Ugly level 38 Eda Gem (insert in bag, destroy)");
		addGem("Ugly level 39 Eda Gem (insert in bag, destroy)");
		addGem("Ugly level 8 Efis Gem (insert in bag, destroy)");
		addGem("Ugly level 13 Efis Gem (insert in bag, destroy)");
		addGem("Beautiful level 13 Efis Gem (insert in bag, destroy)");
		addGem("Ugly level 14 Efis Gem (insert in bag, destroy)");
		addGem("Ugly level 17 Efis Gem (insert in bag, destroy)");
		addGem("Ugly level 19 Efis Gem (insert in bag, destroy)");
		addGem("Ugly level 19 Efis Gem (insert in bag, destroy)");
		addGem("Beautiful level 19 Efis Gem (insert in bag, destroy)");
		addGem("Beautiful level 19 Efis Gem (insert in bag, destroy)");
		addGem("Magnificent level 22 Efis Gem (insert in bag, destroy)");
		addGem("Magnificent level 25 Efis Gem (insert in bag, destroy)");
		addGem("Magnificent level 26 Efis Gem (insert in bag, destroy)");
		addGem("Magnificent level 33 Efis Gem (insert in bag, destroy)");
		addGem("Exquisite level 33 Efis Gem (insert in bag, destroy)");
		addGem("Beautiful level 34 Efis Gem (insert in bag, destroy)");
		addGem("Beautiful level 34 Efis Gem (insert in bag, destroy)");
		addGem("Beautiful level 35 Efis Gem (insert in bag, destroy)");
		addGem("Magnificent level 35 Efis Gem (insert in bag, destroy)");
		addGem("Exquisite level 35 Efis Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Efis Gem (insert in bag, destroy)");
		addGem("Ugly level 37 Efis Gem (insert in bag, destroy)");
		addGem("Exquisite level 52 Efis Gem (insert in bag, destroy)");
		addGem("Exquisite level 52 Efis Gem (insert in bag, destroy)");
		addGem("Exquisite level 52 Efis Gem (insert in bag, destroy)");
		addGem("Magnificent level 56 Efis Gem (insert in bag, destroy)");
		addGem("Magnificent level 56 Efis Gem (insert in bag, destroy)");
		addGem("Magnificent level 56 Efis Gem (insert in bag, destroy)");
		addGem("Magnificent level 57 Efis Gem (insert in bag, destroy)");
		addGem("Ugly level 60 Efis Gem (insert in bag, destroy)");
		addGem("Exquisite level 60 Efis Gem (insert in bag, destroy)");
		addGem("Exquisite level 60 Efis Gem (insert in bag, destroy)");
		addGem("Magnificent level 61 Efis Gem (insert in bag, destroy)");
		addGem("Magnificent level 62 Efis Gem (insert in bag, destroy)");
		addGem("Magnificent level 62 Efis Gem (insert in bag, destroy)");
		addGem("Ugly level 2 Efu Gem (insert in bag, destroy)");
		addGem("Beautiful level 2 Efu Gem (insert in bag, destroy)");
		addGem("Beautiful level 4 Efu Gem (insert in bag, destroy)");
		addGem("Ugly level 9 Efu Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Efu Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Efu Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Efu Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Efu Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Efu Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Efu Gem (insert in bag, destroy)");
		addGem("Ugly level 40 Efu Gem (insert in bag, destroy)");
		addGem("Ugly level 1 Eno Gem (insert in bag, destroy)");
		addGem("Ugly level 1 Eno Gem (insert in bag, destroy)");
		addGem("Ugly level 1 Eno Gem (insert in bag, destroy)");
		addGem("Ugly level 2 Eno Gem (insert in bag, destroy)");
		addGem("Ugly level 2 Eno Gem (insert in bag, destroy)");
		addGem("Ugly level 5 Eno Gem (insert in bag, destroy)");
		addGem("Ugly level 28 Eno Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Eno Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Eno Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Eno Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Eno Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Eno Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Eno Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Eno Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Eno Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Eno Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Eno Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Eno Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Eno Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Eno Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Eno Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Eno Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Eno Gem (insert in bag, destroy)");
		addGem("Ugly level 37 Eno Gem (insert in bag, destroy)");
		addGem("Ugly level 39 Eno Gem (insert in bag, destroy)");
		addGem("Beautiful level 1 Faerh Gem (insert in bag, destroy)");
		addGem("Beautiful level 13 Faerh Gem (insert in bag, destroy)");
		addGem("Magnificent level 13 Faerh Gem (insert in bag, destroy)");
		addGem("Magnificent level 13 Faerh Gem (insert in bag, destroy)");
		addGem("Exquisite level 13 Faerh Gem (insert in bag, destroy)");
		addGem("Ugly level 14 Faerh Gem (insert in bag, destroy)");
		addGem("Ugly level 19 Faerh Gem (insert in bag, destroy)");
		addGem("Beautiful level 21 Faerh Gem (insert in bag, destroy)");
		addGem("Ugly level 22 Faerh Gem (insert in bag, destroy)");
		addGem("Beautiful level 22 Faerh Gem (insert in bag, destroy)");
		addGem("Beautiful level 22 Faerh Gem (insert in bag, destroy)");
		addGem("Ugly level 26 Faerh Gem (insert in bag, destroy)");
		addGem("Ugly level 28 Faerh Gem (insert in bag, destroy)");
		addGem("Beautiful level 29 Faerh Gem (insert in bag, destroy)");
		addGem("Exquisite level 52 Faerh Gem (insert in bag, destroy)");
		addGem("Exquisite level 54 Faerh Gem (insert in bag, destroy)");
		addGem("Magnificent level 59 Faerh Gem (insert in bag, destroy)");
		addGem("Magnificent level 60 Faerh Gem (insert in bag, destroy)");
		addGem("Magnificent level 61 Faerh Gem (insert in bag, destroy)");
		addGem("Magnificent level 62 Faerh Gem (insert in bag, destroy)");
		addGem("Ugly level 13 Fau Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Fau Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Fau Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Fau Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Fau Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Fau Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Fau Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Fau Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Fau Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Fau Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Fau Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Fau Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Fau Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Fau Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Fau Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Fau Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Fau Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Fau Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Fau Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Fau Gem (insert in bag, destroy)");
		addGem("Ugly level 37 Fau Gem (insert in bag, destroy)");
		addGem("Ugly level 37 Fau Gem (insert in bag, destroy)");
		addGem("Ugly level 38 Fau Gem (insert in bag, destroy)");
		addGem("Ugly level 39 Fau Gem (insert in bag, destroy)");
		addGem("Ugly level 45 Fau Gem (insert in bag, destroy)");
		addGem("Ugly level 52 Fau Gem (insert in bag, destroy)");
		addGem("Ugly level 55 Fau Gem (insert in bag, destroy)");
		addGem("Ugly level 61 Fau Gem (insert in bag, destroy)");
		addGem("Ugly level 1 Fen Gem (insert in bag, destroy)");
		addGem("Beautiful level 16 Fen Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Fen Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Fen Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Fen Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Fen Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Fen Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Fen Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Fen Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Fen Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Fen Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Fen Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Fen Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Fen Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Fen Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Fen Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Fen Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Fen Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Fen Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Fen Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Fen Gem (insert in bag, destroy)");
		addGem("Ugly level 39 Fen Gem (insert in bag, destroy)");
		addGem("Ugly level 1 Fih Gem (insert in bag, destroy)");
		addGem("Ugly level 2 Fih Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Fih Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Fih Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Fih Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Fih Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Fih Gem (insert in bag, destroy)");
		addGem("Ugly level 52 Fih Gem (insert in bag, destroy)");
		addGem("Ugly level 55 Fih Gem (insert in bag, destroy)");
		addGem("Ugly level 55 Fih Gem (insert in bag, destroy)");
		addGem("Ugly level 1 Ime Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Ime Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Ime Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Ime Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Ime Gem (insert in bag, destroy)");
		addGem("Magnificent level 36 Ime Gem (insert in bag, destroy)");
		addGem("Ugly level 41 Ime Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Inu Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Inu Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Inu Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Inu Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Inu Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Inu Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Inu Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Inu Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Inu Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Inu Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Inu Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Inu Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Inu Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Inu Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Inu Gem (insert in bag, destroy)");
		addGem("Ugly level 41 Inu Gem (insert in bag, destroy)");
		addGem("Ugly level 45 Inu Gem (insert in bag, destroy)");
		addGem("Beautiful level 45 Inu Gem (insert in bag, destroy)");
		addGem("Ugly level 61 Inu Gem (insert in bag, destroy)");
		addGem("Ugly level 1 Jih Gem (insert in bag, destroy)");
		addGem("Ugly level 1 Jih Gem (insert in bag, destroy)");
		addGem("Ugly level 2 Jih Gem (insert in bag, destroy)");
		addGem("Ugly level 2 Jih Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Jih Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Jih Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Jih Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Jih Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Jih Gem (insert in bag, destroy)");
		addGem("Ugly level 39 Jih Gem (insert in bag, destroy)");
		addGem("Ugly level 45 Jih Gem (insert in bag, destroy)");
		addGem("Magnificent level 4 Kih Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Kih Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Kih Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Kih Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Kih Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Kih Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Kih Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Kih Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Kih Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Kih Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Kih Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Kih Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Kih Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Kih Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Kih Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Kih Gem (insert in bag, destroy)");
		addGem("Ugly level 37 Kih Gem (insert in bag, destroy)");
		addGem("Ugly level 38 Kih Gem (insert in bag, destroy)");
		addGem("Ugly level 42 Kih Gem (insert in bag, destroy)");
		addGem("Ugly level 46 Kih Gem (insert in bag, destroy)");
		addGem("Ugly level 1 Len Gem (insert in bag, destroy)");
		addGem("Ugly level 1 Len Gem (insert in bag, destroy)");
		addGem("Ugly level 2 Len Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Len Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Len Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Len Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Len Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Len Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Len Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Len Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Len Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Len Gem (insert in bag, destroy)");
		addGem("Ugly level 39 Len Gem (insert in bag, destroy)");
		addGem("Ugly level 42 Len Gem (insert in bag, destroy)");
		addGem("Ugly level 53 Len Gem (insert in bag, destroy)");
		addGem("Ugly level 55 Len Gem (insert in bag, destroy)");
		addGem("Ugly level 5 Lua Gem (insert in bag, destroy)");
		addGem("Ugly level 6 Lua Gem (insert in bag, destroy)");
		addGem("Ugly level 8 Lua Gem (insert in bag, destroy)");
		addGem("Ugly level 27 Lua Gem (insert in bag, destroy)");
		addGem("Ugly level 29 Lua Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Lua Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Lua Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Lua Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Lua Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Lua Gem (insert in bag, destroy)");
		addGem("Ugly level 1 Mae Gem (insert in bag, destroy)");
		addGem("Ugly level 2 Mae Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Mae Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Mae Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Mae Gem (insert in bag, destroy)");
		addGem("Ugly level 45 Mae Gem (insert in bag, destroy)");
		addGem("Beautiful level 9 Muena Gem (insert in bag, destroy)");
		addGem("Ugly level 10 Muena Gem (insert in bag, destroy)");
		addGem("Ugly level 13 Muena Gem (insert in bag, destroy)");
		addGem("Ugly level 13 Muena Gem (insert in bag, destroy)");
		addGem("Ugly level 13 Muena Gem (insert in bag, destroy)");
		addGem("Magnificent level 13 Muena Gem (insert in bag, destroy)");
		addGem("Magnificent level 14 Muena Gem (insert in bag, destroy)");
		addGem("Beautiful level 17 Muena Gem (insert in bag, destroy)");
		addGem("Ugly level 21 Muena Gem (insert in bag, destroy)");
		addGem("Ugly level 22 Muena Gem (insert in bag, destroy)");
		addGem("Magnificent level 33 Muena Gem (insert in bag, destroy)");
		addGem("Magnificent level 34 Muena Gem (insert in bag, destroy)");
		addGem("Magnificent level 35 Muena Gem (insert in bag, destroy)");
		addGem("Magnificent level 37 Muena Gem (insert in bag, destroy)");
		addGem("Magnificent level 38 Muena Gem (insert in bag, destroy)");
		addGem("Magnificent level 38 Muena Gem (insert in bag, destroy)");
		addGem("Magnificent level 40 Muena Gem (insert in bag, destroy)");
		addGem("Magnificent level 40 Muena Gem (insert in bag, destroy)");
		addGem("Exquisite level 49 Muena Gem (insert in bag, destroy)");
		addGem("Exquisite level 49 Muena Gem (insert in bag, destroy)");
		addGem("Magnificent level 52 Muena Gem (insert in bag, destroy)");
		addGem("Magnificent level 52 Muena Gem (insert in bag, destroy)");
		addGem("Magnificent level 54 Muena Gem (insert in bag, destroy)");
		addGem("Magnificent level 54 Muena Gem (insert in bag, destroy)");
		addGem("Magnificent level 55 Muena Gem (insert in bag, destroy)");
		addGem("Magnificent level 58 Muena Gem (insert in bag, destroy)");
		addGem("Beautiful level 61 Muena Gem (insert in bag, destroy)");
		addGem("Exquisite level 62 Muena Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Mul Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Mul Gem (insert in bag, destroy)");
		addGem("Ugly level 18 Nax Gem (insert in bag, destroy)");
		addGem("Beautiful level 19 Nefar Gem (insert in bag, destroy)");
		addGem("Beautiful level 19 Nefar Gem (insert in bag, destroy)");
		addGem("Beautiful level 21 Nefar Gem (insert in bag, destroy)");
		addGem("Ugly level 22 Nefar Gem (insert in bag, destroy)");
		addGem("Ugly level 22 Nefar Gem (insert in bag, destroy)");
		addGem("Ugly level 22 Nefar Gem (insert in bag, destroy)");
		addGem("Ugly level 25 Nefar Gem (insert in bag, destroy)");
		addGem("Ugly level 25 Nefar Gem (insert in bag, destroy)");
		addGem("Beautiful level 25 Nefar Gem (insert in bag, destroy)");
		addGem("Ugly level 26 Nefar Gem (insert in bag, destroy)");
		addGem("Beautiful level 28 Nefar Gem (insert in bag, destroy)");
		addGem("Beautiful level 29 Nefar Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Nefar Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Nefar Gem (insert in bag, destroy)");
		addGem("Beautiful level 34 Nefar Gem (insert in bag, destroy)");
		addGem("Beautiful level 35 Nefar Gem (insert in bag, destroy)");
		addGem("Ugly level 38 Nefar Gem (insert in bag, destroy)");
		addGem("Magnificent level 44 Nefar Gem (insert in bag, destroy)");
		addGem("Magnificent level 44 Nefar Gem (insert in bag, destroy)");
		addGem("Magnificent level 44 Nefar Gem (insert in bag, destroy)");
		addGem("Beautiful level 45 Nefar Gem (insert in bag, destroy)");
		addGem("Ugly level 51 Nefar Gem (insert in bag, destroy)");
		addGem("Magnificent level 55 Nefar Gem (insert in bag, destroy)");
		addGem("Magnificent level 55 Nefar Gem (insert in bag, destroy)");
		addGem("Exquisite level 55 Nefar Gem (insert in bag, destroy)");
		addGem("Magnificent level 56 Nefar Gem (insert in bag, destroy)");
		addGem("Magnificent level 56 Nefar Gem (insert in bag, destroy)");
		addGem("Magnificent level 56 Nefar Gem (insert in bag, destroy)");
		addGem("Magnificent level 57 Nefar Gem (insert in bag, destroy)");
		addGem("Ugly level 58 Nefar Gem (insert in bag, destroy)");
		addGem("Ugly level 58 Nefar Gem (insert in bag, destroy)");
		addGem("Ugly level 58 Nefar Gem (insert in bag, destroy)");
		addGem("Beautiful level 58 Nefar Gem (insert in bag, destroy)");
		addGem("Magnificent level 58 Nefar Gem (insert in bag, destroy)");
		addGem("Magnificent level 58 Nefar Gem (insert in bag, destroy)");
		addGem("Exquisite level 58 Nefar Gem (insert in bag, destroy)");
		addGem("Ugly level 59 Nefar Gem (insert in bag, destroy)");
		addGem("Ugly level 59 Nefar Gem (insert in bag, destroy)");
		addGem("Ugly level 60 Nefar Gem (insert in bag, destroy)");
		addGem("Ugly level 60 Nefar Gem (insert in bag, destroy)");
		addGem("Ugly level 60 Nefar Gem (insert in bag, destroy)");
		addGem("Ugly level 60 Nefar Gem (insert in bag, destroy)");
		addGem("Ugly level 60 Nefar Gem (insert in bag, destroy)");
		addGem("Beautiful level 60 Nefar Gem (insert in bag, destroy)");
		addGem("Beautiful level 60 Nefar Gem (insert in bag, destroy)");
		addGem("Beautiful level 61 Nefar Gem (insert in bag, destroy)");
		addGem("Beautiful level 61 Nefar Gem (insert in bag, destroy)");
		addGem("Beautiful level 61 Nefar Gem (insert in bag, destroy)");
		addGem("Magnificent level 61 Nefar Gem (insert in bag, destroy)");
		addGem("Magnificent level 61 Nefar Gem (insert in bag, destroy)");
		addGem("Beautiful level 62 Nefar Gem (insert in bag, destroy)");
		addGem("Magnificent level 62 Nefar Gem (insert in bag, destroy)");
		addGem("Magnificent level 62 Nefar Gem (insert in bag, destroy)");
		addGem("Magnificent level 62 Nefar Gem (insert in bag, destroy)");
		addGem("Magnificent level 62 Nefar Gem (insert in bag, destroy)");
		addGem("Exquisite level 69 Nefar Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Ner Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Ner Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Ner Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Ner Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Ner Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Ner Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Ner Gem (insert in bag, destroy)");
		addGem("Ugly level 61 Ner Gem (insert in bag, destroy)");
		addGem("Ugly level 1 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 1 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 1 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 1 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 2 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 2 Nis Gem (insert in bag, destroy)");
		addGem("Beautiful level 2 Nis Gem (insert in bag, destroy)");
		addGem("Exquisite level 3 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 5 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Nis Gem (insert in bag, destroy)");
		addGem("Beautiful level 30 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 38 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 38 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 39 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 39 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 41 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 42 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 45 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 45 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 47 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 48 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 51 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 52 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 61 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 61 Nis Gem (insert in bag, destroy)");
		addGem("Ugly level 5 Nuy Gem (insert in bag, destroy)");
		addGem("Ugly level 27 Nuy Gem (insert in bag, destroy)");
		addGem("Ugly level 28 Nuy Gem (insert in bag, destroy)");
		addGem("Ugly level 13 Qaera Gem (insert in bag, destroy)");
		addGem("Ugly level 22 Qaera Gem (insert in bag, destroy)");
		addGem("Ugly level 25 Qaera Gem (insert in bag, destroy)");
		addGem("Ugly level 29 Qaera Gem (insert in bag, destroy)");
		addGem("Beautiful level 54 Qaera Gem (insert in bag, destroy)");
		addGem("Exquisite level 55 Qaera Gem (insert in bag, destroy)");
		addGem("Magnificent level 58 Qaera Gem (insert in bag, destroy)");
		addGem("Ugly level 61 Qaera Gem (insert in bag, destroy)");
		addGem("Exquisite level 62 Qaera Gem (insert in bag, destroy)");
		addGem("Ugly level 2 Qah Gem (insert in bag, destroy)");
		addGem("Beautiful level 5 Qah Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Qah Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Qah Gem (insert in bag, destroy)");
		addGem("Ugly level 39 Qah Gem (insert in bag, destroy)");
		addGem("Ugly level 8 Qer Gem (insert in bag, destroy)");
		addGem("Ugly level 11 Qer Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Qer Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Qer Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Qer Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Qer Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Qer Gem (insert in bag, destroy)");
		addGem("Ugly level 42 Qer Gem (insert in bag, destroy)");
		addGem("Beautiful level 25 Qulah Gem (insert in bag, destroy)");
		addGem("Magnificent level 25 Qulah Gem (insert in bag, destroy)");
		addGem("Exquisite level 26 Qulah Gem (insert in bag, destroy)");
		addGem("Ugly level 28 Qulah Gem (insert in bag, destroy)");
		addGem("Ugly level 29 Qulah Gem (insert in bag, destroy)");
		addGem("Ugly level 29 Qulah Gem (insert in bag, destroy)");
		addGem("Ugly level 29 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 29 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 29 Qulah Gem (insert in bag, destroy)");
		addGem("Magnificent level 34 Qulah Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Qulah Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Qulah Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 35 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 35 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 36 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 42 Qulah Gem (insert in bag, destroy)");
		addGem("Exquisite level 54 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 55 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 55 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 55 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 55 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 55 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 55 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 55 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 55 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 56 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 56 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 56 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 56 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 57 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 57 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 57 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 57 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 58 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 59 Qulah Gem (insert in bag, destroy)");
		addGem("Magnificent level 59 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 60 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 60 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 60 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 60 Qulah Gem (insert in bag, destroy)");
		addGem("Magnificent level 60 Qulah Gem (insert in bag, destroy)");
		addGem("Exquisite level 60 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 61 Qulah Gem (insert in bag, destroy)");
		addGem("Beautiful level 61 Qulah Gem (insert in bag, destroy)");
		addGem("Magnificent level 61 Qulah Gem (insert in bag, destroy)");
		addGem("Magnificent level 62 Qulah Gem (insert in bag, destroy)");
		addGem("Exquisite level 62 Qulah Gem (insert in bag, destroy)");
		addGem("Exquisite level 69 Qulah Gem (insert in bag, destroy)");
		addGem("Ugly level 2 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 37 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 40 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 41 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 52 Ruh Gem (insert in bag, destroy)");
		addGem("Ugly level 1 Sah Gem (insert in bag, destroy)");
		addGem("Ugly level 2 Sah Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Sah Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Sah Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Sah Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Sah Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Sah Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Sah Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Sah Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Sah Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Sah Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Sah Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Sah Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Sah Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Sah Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Sah Gem (insert in bag, destroy)");
		addGem("Ugly level 37 Sah Gem (insert in bag, destroy)");
		addGem("Ugly level 38 Sah Gem (insert in bag, destroy)");
		addGem("Ugly level 45 Sah Gem (insert in bag, destroy)");
		addGem("Ugly level 55 Sah Gem (insert in bag, destroy)");
		addGem("Ugly level 55 Sah Gem (insert in bag, destroy)");
		addGem("Ugly level 3 Tur Gem (insert in bag, destroy)");
		addGem("Magnificent level 17 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 37 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 39 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 41 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 45 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 49 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 50 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 61 Tur Gem (insert in bag, destroy)");
		addGem("Ugly level 2 Uax Gem (insert in bag, destroy)");
		addGem("Ugly level 6 Uax Gem (insert in bag, destroy)");
		addGem("Ugly level 15 Uax Gem (insert in bag, destroy)");
		addGem("Ugly level 2 Uka Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Uka Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Uka Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Uka Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Uka Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Uka Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Uka Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Uka Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Uka Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Uka Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Uka Gem (insert in bag, destroy)");
		addGem("Ugly level 44 Uka Gem (insert in bag, destroy)");
		addGem("Beautiful level 5 Urtae Gem (insert in bag, destroy)");
		addGem("Magnificent level 13 Urtae Gem (insert in bag, destroy)");
		addGem("Ugly level 17 Urtae Gem (insert in bag, destroy)");
		addGem("Ugly level 22 Urtae Gem (insert in bag, destroy)");
		addGem("Magnificent level 22 Urtae Gem (insert in bag, destroy)");
		addGem("Beautiful level 25 Urtae Gem (insert in bag, destroy)");
		addGem("Magnificent level 35 Urtae Gem (insert in bag, destroy)");
		addGem("Magnificent level 52 Urtae Gem (insert in bag, destroy)");
		addGem("Ugly level 58 Urtae Gem (insert in bag, destroy)");
		addGem("Beautiful level 61 Urtae Gem (insert in bag, destroy)");
		addGem("Magnificent level 69 Urtae Gem (insert in bag, destroy)");
		addGem("Ugly level 1 Uxi Gem (insert in bag, destroy)");
		addGem("Ugly level 20 Uxi Gem (insert in bag, destroy)");
		addGem("Ugly level 6 Uyi Gem (insert in bag, destroy)");
		addGem("Ugly level 6 Uyi Gem (insert in bag, destroy)");
		addGem("Ugly level 40 Uyi Gem (insert in bag, destroy)");
		addGem("Ugly level 42 Uyi Gem (insert in bag, destroy)");
		addGem("Ugly level 43 Uyi Gem (insert in bag, destroy)");
		addGem("Ugly level 47 Uyi Gem (insert in bag, destroy)");
		addGem("Ugly level 53 Uyi Gem (insert in bag, destroy)");
		addGem("Beautiful level 14 Uza Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Uza Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Uza Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Uza Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Uza Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Uza Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Uza Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Uza Gem (insert in bag, destroy)");
		addGem("Ugly level 2 Vae Gem (insert in bag, destroy)");
		addGem("Ugly level 2 Vae Gem (insert in bag, destroy)");
		addGem("Ugly level 6 Vae Gem (insert in bag, destroy)");
		addGem("Beautiful level 9 Vae Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Vae Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Vae Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Vae Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Vae Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Vae Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Vae Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Vae Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Vae Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Vae Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Vae Gem (insert in bag, destroy)");
		addGem("Ugly level 45 Vae Gem (insert in bag, destroy)");
		addGem("Ugly level 1 Var Gem (insert in bag, destroy)");
		addGem("Ugly level 1 Var Gem (insert in bag, destroy)");
		addGem("Ugly level 1 Var Gem (insert in bag, destroy)");
		addGem("Ugly level 2 Var Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Var Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Var Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Var Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Var Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Var Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Var Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Var Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Var Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Var Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Var Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Var Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Var Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Var Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Var Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Var Gem (insert in bag, destroy)");
		addGem("Ugly level 38 Var Gem (insert in bag, destroy)");
		addGem("Ugly level 40 Var Gem (insert in bag, destroy)");
		addGem("Ugly level 42 Var Gem (insert in bag, destroy)");
		addGem("Ugly level 46 Var Gem (insert in bag, destroy)");
		addGem("Ugly level 10 Xil Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Xil Gem (insert in bag, destroy)");
		addGem("Ugly level 3 Xis Gem (insert in bag, destroy)");
		addGem("Ugly level 22 Xis Gem (insert in bag, destroy)");
		addGem("Ugly level 4 Yar Gem (insert in bag, destroy)");
		addGem("Ugly level 4 Yar Gem (insert in bag, destroy)");
		addGem("Ugly level 6 Yar Gem (insert in bag, destroy)");
		addGem("Ugly level 13 Yar Gem (insert in bag, destroy)");
		addGem("Ugly level 25 Yar Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Yar Gem (insert in bag, destroy)");
		addGem("Ugly level 61 Yar Gem (insert in bag, destroy)");
		addGem("Ugly level 16 Yun Gem (insert in bag, destroy)");
		addGem("Ugly level 20 Yun Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Yun Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Yun Gem (insert in bag, destroy)");
		addGem("Ugly level 47 Yun Gem (insert in bag, destroy)");
		addGem("Ugly level 47 Yun Gem (insert in bag, destroy)");
		addGem("Beautiful level 19 Zaneh Gem (insert in bag, destroy)");
		addGem("Ugly level 21 Zaneh Gem (insert in bag, destroy)");
		addGem("Ugly level 21 Zaneh Gem (insert in bag, destroy)");
		addGem("Ugly level 22 Zaneh Gem (insert in bag, destroy)");
		addGem("Ugly level 22 Zaneh Gem (insert in bag, destroy)");
		addGem("Ugly level 22 Zaneh Gem (insert in bag, destroy)");
		addGem("Ugly level 22 Zaneh Gem (insert in bag, destroy)");
		addGem("Ugly level 22 Zaneh Gem (insert in bag, destroy)");
		addGem("Ugly level 22 Zaneh Gem (insert in bag, destroy)");
		addGem("Beautiful level 22 Zaneh Gem (insert in bag, destroy)");
		addGem("Ugly level 25 Zaneh Gem (insert in bag, destroy)");
		addGem("Ugly level 25 Zaneh Gem (insert in bag, destroy)");
		addGem("Ugly level 25 Zaneh Gem (insert in bag, destroy)");
		addGem("Beautiful level 25 Zaneh Gem (insert in bag, destroy)");
		addGem("Magnificent level 25 Zaneh Gem (insert in bag, destroy)");
		addGem("Beautiful level 26 Zaneh Gem (insert in bag, destroy)");
		addGem("Beautiful level 28 Zaneh Gem (insert in bag, destroy)");
		addGem("Ugly level 29 Zaneh Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Zaneh Gem (insert in bag, destroy)");
		addGem("Beautiful level 36 Zaneh Gem (insert in bag, destroy)");
		addGem("Beautiful level 37 Zaneh Gem (insert in bag, destroy)");
		addGem("Beautiful level 37 Zaneh Gem (insert in bag, destroy)");
		addGem("Beautiful level 37 Zaneh Gem (insert in bag, destroy)");
		addGem("Beautiful level 37 Zaneh Gem (insert in bag, destroy)");
		addGem("Beautiful level 37 Zaneh Gem (insert in bag, destroy)");
		addGem("Beautiful level 37 Zaneh Gem (insert in bag, destroy)");
		addGem("Magnificent level 37 Zaneh Gem (insert in bag, destroy)");
		addGem("Magnificent level 37 Zaneh Gem (insert in bag, destroy)");
		addGem("Magnificent level 37 Zaneh Gem (insert in bag, destroy)");
		addGem("Magnificent level 37 Zaneh Gem (insert in bag, destroy)");
		addGem("Magnificent level 37 Zaneh Gem (insert in bag, destroy)");
		addGem("Magnificent level 37 Zaneh Gem (insert in bag, destroy)");
		addGem("Magnificent level 37 Zaneh Gem (insert in bag, destroy)");
		addGem("Magnificent level 42 Zaneh Gem (insert in bag, destroy)");
		addGem("Magnificent level 48 Zaneh Gem (insert in bag, destroy)");
		addGem("Beautiful level 52 Zaneh Gem (insert in bag, destroy)");
		addGem("Beautiful level 54 Zaneh Gem (insert in bag, destroy)");
		addGem("Beautiful level 60 Zaneh Gem (insert in bag, destroy)");
		addGem("Beautiful level 60 Zaneh Gem (insert in bag, destroy)");
		addGem("Beautiful level 61 Zaneh Gem (insert in bag, destroy)");
		addGem("Beautiful level 2 Zar Gem (insert in bag, destroy)");
		addGem("Beautiful level 2 Zar Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Zar Gem (insert in bag, destroy)");
		addGem("Exquisite level 45 Zar Gem (insert in bag, destroy)");
		addGem("Ugly level 2 Zey Gem (insert in bag, destroy)");
		addGem("Ugly level 26 Zey Gem (insert in bag, destroy)");
		addGem("Beautiful level 28 Zey Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Zey Gem (insert in bag, destroy)");
		addGem("Ugly level 30 Zey Gem (insert in bag, destroy)");
		addGem("Ugly level 31 Zey Gem (insert in bag, destroy)");
		addGem("Ugly level 32 Zey Gem (insert in bag, destroy)");
		addGem("Ugly level 33 Zey Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Zey Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Zey Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Zey Gem (insert in bag, destroy)");
		addGem("Ugly level 34 Zey Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Zey Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Zey Gem (insert in bag, destroy)");
		addGem("Ugly level 35 Zey Gem (insert in bag, destroy)");
		addGem("Ugly level 36 Zey Gem (insert in bag, destroy)");
		addGem("Ugly level 60 Zey Gem (insert in bag, destroy)");
		addGem("");
		addGem("Gem Bag (187) ");
		addGem("");
		addGem("	The gem bag can be used to safely store gems for later use.");
		addGem("");
		addGem("Insert gems in gem bag.");
		addGem("");
		addGem("Remove gems from gem bag.");
		addGem("");
		addGem("Ugly level 32 Aru Gem (remove from bag, destroy)");
		addGem("Ugly level 32 Aru Gem (remove from bag, destroy)");
		addGem("Ugly level 36 Aru Gem (remove from bag, destroy)");
		addGem("Ugly level 38 Aru Gem (remove from bag, destroy)");
		addGem("Ugly level 39 Aru Ruby (remove from bag, destroy)");
		addGem("Ugly level 41 Aru Gem (remove from bag, destroy)");
		addGem("Ugly level 44 Aru Gem (remove from bag, destroy)");
		addGem("Ugly level 45 Aru Gem (remove from bag, destroy)");
		addGem("Ugly level 46 Aru Gem (remove from bag, destroy)");
		addGem("Ugly level 33 Chi Gem (remove from bag, destroy)");
		addGem("Ugly level 35 Chi Gem (remove from bag, destroy)");
		addGem("Ugly level 36 Chi Gem (remove from bag, destroy)");
		addGem("Ugly level 38 Chi Gem (remove from bag, destroy)");
		addGem("Ugly level 38 Chi Gem (remove from bag, destroy)");
		addGem("Ugly level 39 Chi Gem (remove from bag, destroy)");
		addGem("Ugly level 40 Chi Gem (remove from bag, destroy)");
		addGem("Ugly level 44 Chi Gem (remove from bag, destroy)");
		addGem("Ugly level 44 Chi Gem (remove from bag, destroy)");
		addGem("Ugly level 2 Dun Gem (remove from bag, destroy)");
		addGem("Ugly level 34 Dun Gem (remove from bag, destroy)");
		addGem("Ugly level 36 Dun Gem (remove from bag, destroy)");
		addGem("Ugly level 38 Dun Gem (remove from bag, destroy)");
		addGem("Ugly level 39 Dun Ruby (remove from bag, destroy)");
		addGem("Ugly level 34 Eda Gem (remove from bag, destroy)");
		addGem("Ugly level 36 Eda Gem (remove from bag, destroy)");
		addGem("Ugly level 44 Eda Gem (remove from bag, destroy)");
		addGem("Ugly level 37 Efu Gem (remove from bag, destroy)");
		addGem("Ugly level 38 Efu Gem (remove from bag, destroy)");
		addGem("Ugly level 39 Efu Gem (remove from bag, destroy)");
		addGem("Ugly level 39 Efu Gem (remove from bag, destroy)");
		addGem("Ugly level 41 Efu Gem (remove from bag, destroy)");
		addGem("Ugly level 43 Efu Gem (remove from bag, destroy)");
		addGem("Ugly level 34 Eno Gem (remove from bag, destroy)");
		addGem("Ugly level 35 Eno Gem (remove from bag, destroy)");
		addGem("Ugly level 41 Eno Gem (remove from bag, destroy)");
		addGem("Ugly level 41 Eno Gem (remove from bag, destroy)");
		addGem("Ugly level 41 Eno Gem (remove from bag, destroy)");
		addGem("Ugly level 42 Eno Gem (remove from bag, destroy)");
		addGem("Ugly level 43 Eno Gem (remove from bag, destroy)");
		addGem("Ugly level 43 Eno Gem (remove from bag, destroy)");
		addGem("Ugly level 46 Eno Gem (remove from bag, destroy)");
		addGem("Ugly level 33 Fau Gem (remove from bag, destroy)");
		addGem("Ugly level 34 Fau Ruby (remove from bag, destroy)");
		addGem("Ugly level 35 Fau Gem (remove from bag, destroy)");
		addGem("Ugly level 35 Fau Gem (remove from bag, destroy)");
		addGem("Ugly level 35 Fau Gem (remove from bag, destroy)");
		addGem("Beautiful level 35 Fau Gem (remove from bag, destroy)");
		addGem("Ugly level 43 Fau Gem (remove from bag, destroy)");
		addGem("Ugly level 2 Fen Gem (remove from bag, destroy)");
		addGem("Ugly level 32 Fen Gem (remove from bag, destroy)");
		addGem("Ugly level 33 Fen Gem (remove from bag, destroy)");
		addGem("Ugly level 39 Fen Gem (remove from bag, destroy)");
		addGem("Ugly level 39 Fen Gem (remove from bag, destroy)");
		addGem("Ugly level 42 Fen Gem (remove from bag, destroy)");
		addGem("Ugly level 38 Fih Gem (remove from bag, destroy)");
		addGem("Ugly level 39 Fih Gem (remove from bag, destroy)");
		addGem("Ugly level 39 Fih Gem (remove from bag, destroy)");
		addGem("Ugly level 40 Fih Gem (remove from bag, destroy)");
		addGem("Ugly level 41 Fih Gem (remove from bag, destroy)");
		addGem("Ugly level 46 Fih Gem (remove from bag, destroy)");
		addGem("Ugly level 46 Fih Gem (remove from bag, destroy)");
		addGem("Ugly level 46 Fih Gem (remove from bag, destroy)");
		addGem("Ugly level 39 Ime Gem (remove from bag, destroy)");
		addGem("Ugly level 39 Ime Gem (remove from bag, destroy)");
		addGem("Ugly level 33 Inu Gem (remove from bag, destroy)");
		addGem("Ugly level 33 Inu Ruby (remove from bag, destroy)");
		addGem("Ugly level 36 Inu Gem (remove from bag, destroy)");
		addGem("Ugly level 38 Inu Gem (remove from bag, destroy)");
		addGem("Ugly level 39 Inu Gem (remove from bag, destroy)");
		addGem("Ugly level 40 Inu Gem (remove from bag, destroy)");
		addGem("Ugly level 40 Inu Gem (remove from bag, destroy)");
		addGem("Ugly level 41 Inu Gem (remove from bag, destroy)");
		addGem("Ugly level 41 Inu Gem (remove from bag, destroy)");
		addGem("Ugly level 33 Kih Gem (remove from bag, destroy)");
		addGem("Ugly level 35 Kih Gem (remove from bag, destroy)");
		addGem("Ugly level 35 Kih Gem (remove from bag, destroy)");
		addGem("Ugly level 38 Kih Gem (remove from bag, destroy)");
		addGem("Ugly level 38 Kih Gem (remove from bag, destroy)");
		addGem("Ugly level 43 Kih Gem (remove from bag, destroy)");
		addGem("Beautiful level 44 Kih Gem (remove from bag, destroy)");
		addGem("Ugly level 45 Kih Gem (remove from bag, destroy)");
		addGem("Ugly level 33 Len Gem (remove from bag, destroy)");
		addGem("Ugly level 39 Len Gem (remove from bag, destroy)");
		addGem("Ugly level 41 Len Gem (remove from bag, destroy)");
		addGem("Ugly level 44 Len Gem (remove from bag, destroy)");
		addGem("Ugly level 31 Lua Gem (remove from bag, destroy)");
		addGem("Ugly level 33 Lua Gem (remove from bag, destroy)");
		addGem("Ugly level 35 Lua Gem (remove from bag, destroy)");
		addGem("Ugly level 38 Lua Gem (remove from bag, destroy)");
		addGem("Ugly level 40 Lua Gem (remove from bag, destroy)");
		addGem("Ugly level 41 Lua Gem (remove from bag, destroy)");
		addGem("Ugly level 44 Lua Gem (remove from bag, destroy)");
		addGem("Ugly level 8 Mul Gem (remove from bag, destroy)");
		addGem("Ugly level 34 Mul Gem (remove from bag, destroy)");
		addGem("Ugly level 36 Ner Gem (remove from bag, destroy)");
		addGem("Ugly level 39 Ner Gem (remove from bag, destroy)");
		addGem("Ugly level 40 Ner Gem (remove from bag, destroy)");
		addGem("Ugly level 40 Ner Gem (remove from bag, destroy)");
		addGem("Ugly level 41 Ner Gem (remove from bag, destroy)");
		addGem("Ugly level 46 Ner Gem (remove from bag, destroy)");
		addGem("Ugly level 34 Nis Gem (remove from bag, destroy)");
		addGem("Ugly level 36 Nis Gem (remove from bag, destroy)");
		addGem("Ugly level 36 Nis Gem (remove from bag, destroy)");
		addGem("Ugly level 38 Nis Gem (remove from bag, destroy)");
		addGem("Ugly level 39 Nis Gem (remove from bag, destroy)");
		addGem("Ugly level 39 Nis Ruby (remove from bag, destroy)");
		addGem("Ugly level 42 Nis Gem (remove from bag, destroy)");
		addGem("Ugly level 45 Nis Gem (remove from bag, destroy)");
		addGem("Ugly level 46 Nis Gem (remove from bag, destroy)");
		addGem("Ugly level 46 Nis Gem (remove from bag, destroy)");
		addGem("Ugly level 31 Qah Gem (remove from bag, destroy)");
		addGem("Beautiful level 3 Qer Gem (remove from bag, destroy)");
		addGem("Ugly level 4 Qer Gem (remove from bag, destroy)");
		addGem("Ugly level 40 Qer Gem (remove from bag, destroy)");
		addGem("Ugly level 46 Qer Gem (remove from bag, destroy)");
		addGem("Ugly level 34 Ruh Gem (remove from bag, destroy)");
		addGem("Ugly level 34 Ruh Gem (remove from bag, destroy)");
		addGem("Ugly level 35 Ruh Gem (remove from bag, destroy)");
		addGem("Ugly level 36 Ruh Gem (remove from bag, destroy)");
		addGem("Ugly level 38 Ruh Gem (remove from bag, destroy)");
		addGem("Ugly level 38 Ruh Gem (remove from bag, destroy)");
		addGem("Ugly level 39 Ruh Gem (remove from bag, destroy)");
		addGem("Ugly level 39 Ruh Gem (remove from bag, destroy)");
		addGem("Ugly level 40 Ruh Gem (remove from bag, destroy)");
		addGem("Ugly level 40 Ruh Gem (remove from bag, destroy)");
		addGem("Ugly level 45 Ruh Gem (remove from bag, destroy)");
		addGem("Ugly level 46 Ruh Gem (remove from bag, destroy)");
		addGem("Ugly level 30 Sah Gem (remove from bag, destroy)");
		addGem("Ugly level 34 Sah Gem (remove from bag, destroy)");
		addGem("Ugly level 35 Sah Gem (remove from bag, destroy)");
		addGem("Ugly level 36 Sah Gem (remove from bag, destroy)");
		addGem("Ugly level 38 Sah Gem (remove from bag, destroy)");
		addGem("Ugly level 39 Sah Gem (remove from bag, destroy)");
		addGem("Ugly level 39 Sah Gem (remove from bag, destroy)");
		addGem("Ugly level 40 Sah Gem (remove from bag, destroy)");
		addGem("Ugly level 41 Sah Gem (remove from bag, destroy)");
		addGem("Ugly level 41 Sah Gem (remove from bag, destroy)");
		addGem("Ugly level 42 Sah Gem (remove from bag, destroy)");
		addGem("Ugly level 44 Sah Gem (remove from bag, destroy)");
		addGem("Ugly level 45 Sah Gem (remove from bag, destroy)");
		addGem("Ugly level 46 Sah Gem (remove from bag, destroy)");
		addGem("Ugly level 30 Tur Gem (remove from bag, destroy)");
		addGem("Ugly level 31 Tur Gem (remove from bag, destroy)");
		addGem("Ugly level 31 Tur Gem (remove from bag, destroy)");
		addGem("Ugly level 35 Tur Gem (remove from bag, destroy)");
		addGem("Ugly level 41 Tur Gem (remove from bag, destroy)");
		addGem("Ugly level 43 Tur Gem (remove from bag, destroy)");
		addGem("Ugly level 44 Tur Gem (remove from bag, destroy)");
		addGem("Beautiful level 45 Tur Gem (remove from bag, destroy)");
		addGem("Ugly level 1 Uka Gem (remove from bag, destroy)");
		addGem("Ugly level 34 Uka Gem (remove from bag, destroy)");
		addGem("Ugly level 37 Uka Gem (remove from bag, destroy)");
		addGem("Ugly level 38 Uka Gem (remove from bag, destroy)");
		addGem("Ugly level 33 Uyi Gem (remove from bag, destroy)");
		addGem("Ugly level 40 Uza Gem (remove from bag, destroy)");
		addGem("Ugly level 40 Uza Gem (remove from bag, destroy)");
		addGem("Ugly level 32 Vae Gem (remove from bag, destroy)");
		addGem("Ugly level 35 Vae Gem (remove from bag, destroy)");
		addGem("Ugly level 35 Vae Gem (remove from bag, destroy)");
		addGem("Ugly level 37 Vae Gem (remove from bag, destroy)");
		addGem("Ugly level 40 Vae Gem (remove from bag, destroy)");
		addGem("Ugly level 43 Vae Gem (remove from bag, destroy)");
		addGem("Ugly level 43 Vae Gem (remove from bag, destroy)");
		addGem("Ugly level 45 Vae Gem (remove from bag, destroy)");
		addGem("Ugly level 46 Vae Gem (remove from bag, destroy)");
		addGem("Ugly level 39 Var Ruby (remove from bag, destroy)");
		addGem("Ugly level 41 Var Gem (remove from bag, destroy)");
		addGem("Ugly level 46 Var Gem (remove from bag, destroy)");
		addGem("Ugly level 33 Yar Gem (remove from bag, destroy)");
		addGem("Ugly level 38 Yar Gem (remove from bag, destroy)");
		addGem("Ugly level 39 Yar Gem (remove from bag, destroy)");
		addGem("Ugly level 40 Yar Gem (remove from bag, destroy)");
		addGem("Ugly level 44 Yar Gem (remove from bag, destroy)");
		addGem("Ugly level 19 Yun Gem (remove from bag, destroy)");
		addGem("Ugly level 31 Yun Gem (remove from bag, destroy)");
		addGem("Ugly level 33 Yun Ruby (remove from bag, destroy)");
		addGem("Ugly level 39 Yun Gem (remove from bag, destroy)");
		addGem("Magnificent level 58 Zaneh Ruby (remove from bag, destroy)");
		addGem("Magnificent level 59 Zaneh Ruby (remove from bag, destroy)");
		addGem("Beautiful level 3 Zar Gem (remove from bag, destroy)");
		addGem("Ugly level 19 Zar Gem (remove from bag, destroy)");
		addGem("Ugly level 37 Zar Gem (remove from bag, destroy)");
		addGem("Ugly level 39 Zar Gem (remove from bag, destroy)");
		addGem("Ugly level 37 Zey Gem (remove from bag, destroy)");
		addGem("Ugly level 39 Zey Gem (remove from bag, destroy)");
		addGem("Ugly level 40 Zey Gem (remove from bag, destroy)");
		addGem("Ugly level 45 Zey Gem (remove from bag, destroy)");

    	for (Iterator<Orb> i = orbs.iterator(); i.hasNext();) {
    		Orb o = i.next();
    		boolean add=true;
    		for (Iterator<String> ii = o.getGemsigns().iterator(); ii.hasNext();) {
    			String s = ii.next();
    			if (gems.get(s) == null) {
    				add=false;
    				//System.out.println("gem not found: "+s);
    				//break;
    			}
    		}
    		if (add) addOrb(o);
    	}

	}
	
	public void printOrbs() {
		System.out.println("Orbs:");
		int cnt=0;
    	for (Iterator<Orb> i = orbs.iterator(); i.hasNext(); cnt++) {
    		System.out.println(cnt+":"+i.next());
    	}
	}
	public void printGems() {
		System.out.println("Gems:");
		for (Iterator<String> i= gems.keySet().iterator(); i.hasNext();) {
			for (Iterator<Gem> gi = gems.get(i.next()).iterator(); gi.hasNext();) {
				System.out.println(gi.next().toCompactString());
			}
		}
	}
	
	public void compare() {
//		long one = System.currentTimeMillis();
//    	NodeComparator comparator = new NodeComparator();
//    	if (0 == 0) {
//    		comparator = new NodeComparator() {
//	    		public int compare(Object o1, Object o2) {
//	    			return ((OrbNode)o2).getTreePower()-((OrbNode)o1).getTreePower();
//	    		}
//    		};
//    	}
//		Tree t = new BeamSearchTree2(orbs,gems,30,comparator,true);
		
//		OrbNode n = t.search();
		//int totalpower = n.getTreePower();
//		while (n != null) {
//			System.out.println(orbs.get(n.getId()));
//			n = n.getParent();
//		}

		//System.out.println("total power: "+totalpower);
		
//		long two = System.currentTimeMillis();
//		System.out.println("took me "+(two-one)+" ms to calculate");
//		System.out.println("I expanded "+(t.getTotalnodes())+" nodes");
	}
    public static void main(String[] args) {
    	OrbParser op = new OrbParser();
    	op.go();
//    	System.out.println("---------");
//    	op.printOrbs();
//    	op.printGems();
    	System.out.println("---------");
    	op.compare();
    } 
	
		

    
}
